sports = {
"1":"81diver",
"2":"Abu-san",
"3":"Ace of Diamond",
"4":"Aim for the Ace!",
"5":"Air Gear",
"6":"Akakichi no Eleven",
"7":"All Out!!",
"8":"Amanchu!",
"9":"Angels in the Court",
"10":"Animal Olympic Games",
"11":"Anima Yell!",
"12":"Arrow Emblem: Hawk of the Grand Prix",
"13":"Asahinagu",
"14":"Ashen Victor",
"15":"Ashita e Kick-off",
"16":"Ashita no Joe",
"17":"Attack No. 1",
"18":"Attack on Tomorrow",
"19":"Attacker You!",
"20":"Baby Steps",
"21":"Badminton Girl",
"22":"Baki the Grappler",
"23":"Bamboo Blade",
"24":"Bataashi Kingyo",
"25":"Big Windup!",
"26":"Blazing Transfer Student",
"27":"Break Shot",
"28":"Buzzer Beater",
"29":"Capeta",
"30":"Captain Tsubasa",
"31":"Cheer Boys!!",
"32":"Chihayafuru",
"33":"Crimson Hero",
"34":"Cross Game",
"35":"Cross Manage",
"36":"Dan Doh!!",
"37":"Dash!",
"38":"Dash Kappei",
"39":"Days",
"40":"Dear Boys",
"41":"Dive!!",
"42":"Dokaben",
"43":"Eyeshield 21",
"44":"Football Hawk",
"45":"Free!",
"46":"Ganba! Fly High",
"47":"Ganbare!! Tabuchi-kun!!",
"48":"Giant Killing",
"49":"Ginban Kaleidoscope",
"50":"Girl Got Game",
"51":"Go!! Southern Ice Hockey Club",
"52":"Gurazeni",
"53":"H2",
"54":"Haikyu!!",
"55":"Hajime no Ippo",
"56":"Hana-Kimi",
"57":"Hanebado!",
"58":"Harlem Beat",
"59":"Hikari no Densetsu",
"60":"Hikaru no Go",
"61":"Hinomaru Sumo",
"62":"How Heavy Are the Dumbbells You Lift?",
"63":"I'll",
"64":"Igaguri-kun [jp]",
"65":"Inazuma Eleven",
"66":"Initial D",
"67":"Inu Neko Jump!",
"68":"Iwa-Kakeru! -Climbing Girls-",
"69":"Jaja Uma Grooming Up!",
"70":"Karate Master",
"71":"Kenkō Zenrakei Suieibu Umishō",
"72":"King of Prism",
"73":"Kinnikuman",
"74":"Kizuna: Bonds of Love",
"75":"Kuroko's Basketball",
"76":"Mahjong Hishō-den: Naki no Ryū",
"77":"Major",
"78":"March Comes in Like a Lion",
"79":"Mars",
"80":"Megalo Box",
"81":"Midori no Makibaō",
"82":"Monkey Turn",
"83":"Musashi no Ken",
"84":"My Heavenly Hockey Club",
"85":"Nana Maru San Batsu",
"86":"Nononono",
"87":"One Outs",
"88":"One-pound Gospel",
"89":"Over Drive",
"90":"Ping Pong",
"91":"Pretty Rhythm",
"92":"Pretty Rhythm: Aurora Dream",
"93":"Pretty Rhythm: Dear My Future",
"94":"Pretty Rhythm: Rainbow Live",
"95":"Pretty Rhythm: All Star Selection",
"96":"The Prince of Tennis",
"97":"Princess Nine",
"98":"Pro Golfer Saru [jp]",
"99":"Real",
"100":"Rideback",
"101":"Rifle is Beautiful",
"102":"Ring ni Kakero",
"103":"Rough",
"104":"The Ryuo's Work is Never Done!",
"105":"Sabagebu!",
"106":"Saki",
"107":"Shion no Ō",
"108":"Shōjo Fight [jp]",
"109":"Slam Dunk",
"110":"Slow Step",
"111":"Speed Racer",
"112":"Star of the Giants",
"113":"Stella Women's Academy, High School Division Class C3",
"114":"Sugar Princess",
"115":"Super Yo-Yo",
"116":"Supinamarada!",
"117":"Suzuka",
"118":"Tiger Mask",
"119":"Touch",
"120":"Tough",
"121":"Tsurune",
"122":"Uma Musume Pretty Derby",
"123":"Waiting for Spring",
"124":"Welcome to the Ballroom",
"125":"Whistle!",
"126":"Yawara!",
"127":"Yowamushi Pedal",
"128":"Yuri on Ice"
}

action = {
"1": "Abashiri Family" ,
"2": "Absolute Duo",
"3": "A Certain Magical Index",
"4": "A Certain Magical Index II",
"5": "A Certain Magical Index: The Movie - The Miracle of Endymion",
"6": "A Certain Scientific Railgun",
"7": "A Certain Scientific Railgun",
"8": "A Certain Scientific Railgun",
"9": "AD Police",
"10": "A.D. Police: To Protect and Serve",
"11": "Aesthetica of a Rogue Hero",
"12": "Afro Samurai",
"13": "Afro Samurai: Resurrection",
"14": "Agent Aika",
"15": "Akira",
"16": "Angel Beats!",
"17": "Angel Beats! Stairway to Heaven",
"18": "Angel Beats! Hell's Kitchen",
"19": "Arabian Nights: Sinbad's Adventures",
"20": "Armitage III",
"21": "Armitage III: Poly-Matrix",
"22": "Armitage III: Dual-Matrix",
"23": "Armored Trooper Votoms",
"24": "Attack on Titan",
"25": "Attack on Titan: Part 1: Crimson Bow and Arrow",
"26": "Attack on Titan: Part 2: Wings of Freedom",
"27": "Baccano",
"28": "Battle Royal High School",
"29": "Berserk (1997)",
"30": "Berserk (2016)",
"31": "Black Jack 21",
"32": "Black Lagoon",
"33": "Black Lagoon: The Second Barrage",
"34": "Black Lagoon: Roberta's Blood Trail",
"35": "Black Magic M-66",
"36": "Black Rock Shooter",
"37": "Black Rock Shooter",
"38": "Blade of the Immortal",
"39": "Blassreiter",
"40": "Bleach",
"41": "Bleach: Memories of Nobody",
"42": "Bleach: The DiamondDust Rebellion",
"43": "Bleach: Fade to Black",
"44": "Bleach: Hell Verse",
"45": "Blood+",
"46": "Blood-C",
"47": "Blood-C: The Last Dark",
"48": "Blood: The Last Vampire",
"49": "Blue Exorcist",
"50": "Blue Exorcist: The Movie",
"51": "Blue Exorcist: Kyoto Impure King Arc",
"52": "Blue Seed",
"53": "Blue Seed Beyond",
"54": "Btooom!",
"55": "Burn-Up Scramble",
"56": "Burst Angel",
"57": "Burst Angel - Episode Zero: Infinity",
"58": "Busou Renkin",
"59": "Cardfight! Vanguard",
"60": "Cardfight! Vanguard: Asia Circuit",
"61": "Cardfight! Vanguard: Link Joker",
"62": "Cardfight! Vanguard: Legion Mate",
"63": "Cardfight! Vanguard G",
"64": "Cardfight! Vanguard G: GIRS Crisis",
"65": "Cardfight! Vanguard G: Stride Gate",
"66": "Cardfight! Vanguard G NEXT",
"67": "Casshern Sins",
"68": "The Castle Of Cagliostro",
"69": "Chrome Shelled Regios",
"70": "Claymore",
"71": "Cutey Honey",
"72": "Cybuster",
"73": "Dance In The Vampire Bund",
"74": "Darker Than Black",
"75": "Darker Than Black: Beneath the Fully Bloomed Cherry Blossoms",
"76": "Darker Than Black: Gemini of the Meteor",
"77": "Darker Than Black: Origins",
"78": "Daughter of Twenty Faces",
"79": "Devil Hunter Yohko",
"80": "Devilman",
"81": "Devilman: The Birth",
"82": "Devilman: Demon Bird Sirene",
"83": "Digimon Adventure",
"84": "Digimon Adventure 02",
"85": "Digimon Adventure Tri.",
"86": "Digimon Data Squad",
"87": "Digimon Frontier",
"88": "Digimon Fusion",
"89": "Digimon Tamers",
"90": "Digimon Universe: Appli Monsters",
"91": "Dirty Pair",
"92": "Dirty Pair 2",
"93": "Dirty Pair: Affair of Nolandia",
"94": "Dirty Pair Flash",
"95": "Dirty Pair: Flight 005 Conspiracy",
"96": "Dirty Pair: Project Eden",
"97": "Dominion",
"98": "New Dominion: Tank Police",
"99": "Dragon Ball",
"100": "Dragon Ball GT",
"101": "Dragon Ball Super",
"102": "Dragon Ball Z",
"103": "Dragon Ball Z Kai",
"104": "Fullmetal Alchemist",
"105": "Fullmetal Alchemist: Brotherhood",
"106": "GetBackers",
"107": "Gurren Lagann",
"108": "Hajime no Ippo",
"109": "Hellsing",
"110": "JoJo's Bizarre Adventure",
"111": "JoJo's Bizarre Adventure: Adventure",
"112": "JoJo's Bizarre Adventure: Phantom Blood",
"113": "JoJo´s Bizarre Adventure: Stardust Crusaders",
"114": "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
"115": "Naruto",
"116": "Naruto Shippuden",
"117": "One Piece",
"118": "Sonic X",
"119": "Sorcerous Stabber Orphen: Beginning",
"120": "Sorcerous Stabber Orphen: Revenge",
"121": "Sorcerous Stabber Orphen: Wayward Journey",
"122": "Soul Eater",
"123": "Sword Art Online",
"124": "Sword Art Online II",
"125": "Trinity Blood",
"126": "Neon Genesis Evangelion",
"127": "Virtua Fighter",
"128": "mob psycho 100"
}

sports = {
"1":"81diver",
"2":"Abu-san",
"3":"Ace of Diamond",
"4":"Aim for the Ace!",
"5":"Air Gear",
"6":"Akakichi no Eleven",
"7":"All Out!!",
"8":"Amanchu!",
"9":"Angels in the Court",
"10":"Animal Olympic Games",
"11":"Anima Yell!",
"12":"Arrow Emblem: Hawk of the Grand Prix",
"13":"Asahinagu",
"14":"Ashen Victor",
"15":"Ashita e Kick-off",
"16":"Ashita no Joe",
"17":"Attack No. 1",
"18":"Attack on Tomorrow",
"19":"Attacker You!",
"20":"Baby Steps",
"21":"Badminton Girl",
"22":"Baki the Grappler",
"23":"Bamboo Blade",
"24":"Bataashi Kingyo",
"25":"Big Windup!",
"26":"Blazing Transfer Student",
"27":"Break Shot",
"28":"Buzzer Beater",
"29":"Capeta",
"30":"Captain Tsubasa",
"31":"Cheer Boys!!",
"32":"Chihayafuru",
"33":"Crimson Hero",
"34":"Cross Game",
"35":"Cross Manage",
"36":"Dan Doh!!",
"37":"Dash!",
"38":"Dash Kappei",
"39":"Days",
"40":"Dear Boys",
"41":"Dive!!",
"42":"Dokaben",
"43":"Eyeshield 21",
"44":"Football Hawk",
"45":"Free!",
"46":"Ganba! Fly High",
"47":"Ganbare!! Tabuchi-kun!!",
"48":"Giant Killing",
"49":"Ginban Kaleidoscope",
"50":"Girl Got Game",
"51":"Go!! Southern Ice Hockey Club",
"52":"Gurazeni",
"53":"H2",
"54":"Haikyu!!",
"55":"Hajime no Ippo",
"56":"Hana-Kimi",
"57":"Hanebado!",
"58":"Harlem Beat",
"59":"Hikari no Densetsu",
"60":"Hikaru no Go",
"61":"Hinomaru Sumo",
"62":"How Heavy Are the Dumbbells You Lift?",
"63":"I'll",
"64":"Igaguri-kun [jp]",
"65":"Inazuma Eleven",
"66":"Initial D",
"67":"Inu Neko Jump!",
"68":"Iwa-Kakeru! -Climbing Girls-",
"69":"Jaja Uma Grooming Up!",
"70":"Karate Master",
"71":"Kenkō Zenrakei Suieibu Umishō",
"72":"King of Prism",
"73":"Kinnikuman",
"74":"Kizuna: Bonds of Love",
"75":"Kuroko's Basketball",
"76":"Mahjong Hishō-den: Naki no Ryū",
"77":"Major",
"78":"March Comes in Like a Lion",
"79":"Mars",
"80":"Megalo Box",
"81":"Midori no Makibaō",
"82":"Monkey Turn",
"83":"Musashi no Ken",
"84":"My Heavenly Hockey Club",
"85":"Nana Maru San Batsu",
"86":"Nononono",
"87":"One Outs",
"88":"One-pound Gospel",
"89":"Over Drive",
"90":"Ping Pong",
"91":"Pretty Rhythm",
"92":"Pretty Rhythm: Aurora Dream",
"93":"Pretty Rhythm: Dear My Future",
"94":"Pretty Rhythm: Rainbow Live",
"95":"Pretty Rhythm: All Star Selection",
"96":"The Prince of Tennis",
"97":"Princess Nine",
"98":"Pro Golfer Saru [jp]",
"99":"Real",
"100":"Rideback",
"101":"Rifle is Beautiful",
"102":"Ring ni Kakero",
"103":"Rough",
"104":"The Ryuo's Work is Never Done!",
"105":"Sabagebu!",
"106":"Saki",
"107":"Shion no Ō",
"108":"Shōjo Fight [jp]",
"109":"Slam Dunk",
"110":"Slow Step",
"111":"Speed Racer",
"112":"Star of the Giants",
"113":"Stella Women's Academy, High School Division Class C3",
"114":"Sugar Princess",
"115":"Super Yo-Yo",
"116":"Supinamarada!",
"117":"Suzuka",
"118":"Tiger Mask",
"119":"Touch",
"120":"Tough",
"121":"Tsurune",
"122":"Uma Musume Pretty Derby",
"123":"Waiting for Spring",
"124":"Welcome to the Ballroom",
"125":"Whistle!",
"126":"Yawara!",
"127":"Yowamushi Pedal",
"128":"Yuri on Ice"
}

sliceoflife = {
"1":"High School! Kimengumi",
"2":"Yokohama Kaidashi Kikō",
"3":"Kokoro Toshokan",
"4":"Shrine of the Morning Mist",
"5":"Azumanga Daioh",
"6":"Quiet Country Cafe",
"7":"Aria",
"8":"Strawberry Marshmallow",
"9":"Bartender",
"10":"Dobutsu no Mori",
"11":"Clannad",
"12":"Lucky Star",
"13":"Minami-ke",
"14":"Sketchbook ~full color's~",
"15":"Hyakko",
"16":"GA Geijutsuka Art Design Class",
"17":"Hidamari Sketch",
"18":"K-On!",
"19":"Ristorante Paradiso",
"20":"Student Council's Discretion",
"21":"And Yet the Town Moves",
"22":"Bakuman",
"23":"Mitsudomoe",
"24":"Tamayura",
"25":"Squid Girl",
"26":"Working!!",
"27":"A Channel",
"28":"Anohana: The Flower We Saw That Day",
"29":"From Up on Poppy Hill",
"30":"Hanasaku Iroha",
"31":"Nichijou",
"32":"Tamayura: Hitotose",
"33":"YuruYuri",
"34":"Daily Lives of High School Boys",
"35":"Hidamari Sketch x Honeycomb",
"36":"Hyōka",
"37":"Kill Me Baby",
"38":"Kimi to Boku 2",
"39":"Mysterious Girlfriend X",
"40":"Place to Place",
"41":"Shirokuma Cafe",
"42":"Teekyu",
"43":"Wolf Children",
"44":"Yurumates 3D",
"45":"Free!",
"46":"Genshiken: Second Season",
"47":"GJ Club",
"48":"Kin-iro Mosaic",
"49":"Kotoura-san",
"50":"Love Live!",
"51":"Minami-ke: Tadaima",
"52":"My Teen Romantic Comedy SNAFU",
"53":"Non Non Biyori",
"54":"Servant x Service",
"55":"Silver Spoon",
"56":"Super Seisyun Brothers",
"57":"Tamako Market",
"58":"Tamayura: More Aggressive",
"59":"WataMote",
"60":"The Wind Rises",
"61":"Yuyushiki",
"62":"Barakamon",
"63":"The Comic Artist and His Assistants",
"64":"Engaged to the Unidentified",
"65":"Free! - Eternal Summer",
"66":"Is the Order a Rabbit?",
"67":"My Neighbor Seki",
"68":"Go! Go! 575",
"69":"Soul Eater Not!",
"70":"Tesagure! Bukatsu-mono Encore",
"71":"Wake Up, Girls!",
"72":"Food Wars!: Shokugeki no Soma",
"73":"Castle Town Dandelion",
"74":"Himouto! Umaru-chan",
"75":"School-Live!",
"76":"Sound! Euphonium",
"77":"Anne Happy",
"78":"Haven't You Heard? I'm Sakamoto",
"79":"Tanaka-kun is Always Listless",
"80":"A Centaur's Life",
"81":"Gabriel DropOut",
"82":"Blend S",
"83":"Uzaki-chan Wants to Hang Out!"
}

horror = {
"17":"Danganronpa: The Animation",
"18":"Dark Cat",
"19":"Demon City Shinjuku",
"20":"Demon Lord Dante",
"21":"Demon Prince Enma",
"22":"Digital Devil Story: Megami Tensei",
"23":"Doomed Megalopolis",
"24":"Elfen Lied",
"25":"Future Diary",
"26":"Gantz",
"27":"Highschool of the Dead",
"28":"Gregory Horror Show",
"29":"Galerians: Rion",
"30":"Genocyber",
"31":"Ghost Hunt",
"32":"Hakaba Kitaro (GeGeGe no Kitaro)",
"33":"Happy Sugar Life",
"34":"Hellsing",
"35":"Hellsing Ultimate",
"36":"Hell Target",
"37":"Higurashi When They Cry",
"38":"Interlude",
"39":"Jigokudou Reikai Tsuushin",
"40":"Judge",
"41":"Kakurenbo: Hide & Seek",
"42":"The Laughing Salesman",
"43":"Laughing Target",
"44":"Le Portrait de Petit Cossette",
"45":"Lily C.A.T.",
"46":"Malice@Doll",
"47":"Mermaid's Forest",
"48":"Mermaid's Scar",
"49":"Mermaid's Forest",
"50":"Mononoke",
"51":"Monster",
"52":"Monster of Frankenstein",
"53":"Mōryō no Hako",
"54":"Night Head Genesis",
"55":"Ogre Slayer",
"56":"Ookami Kakushi",
"57":"Ousama Game",
"58":"Parasyte: The Maxim",
"59":"Pet Shop of Horrors",
"60":"Pupa",
"61":"Puppet Princess",
"62":"Requiem from the Darkness",
"63":"Roots Search",
"64":"Shadow Star Narutaru",
"65":"Shiki",
"66":"Shin Megami Tensei: Tokyo Mokushiroku",
"67":"SoulTaker",
"68":"Terra Formars",
"69":"Terra Formars: Revenge",
"70":"Thriller Restaurant",
"71":"Tokko",
"72":"Tokyo Ghoul",
"73":"Tokyo Majin",
"74":"Tokyo Majin: 2nd Act",
"75":"Twilight of the Dark Master",
"76":"Violence Jack: Harem Bomber",
"77":"Violence Jack: Evil Town",
"78":"Violence Jack: Hell's Wind Hen",
"79":"Wasurenagumo",
"80":"Wicked City",
"81":"Uzumaki"
}

scifi = {
"1":"Astro Boy",
"2":"8 Man",
"3":"Big X",
"4":"The Amazing 3",
"5":"Be Forever Yamato",
"6":"Astro Boy",
"7":"Urusei Yatsura",
"8":"Andromeda Stories",
"9":"Arcadia of My Youth",
"10":"Arcadia of My Youth: Endless Orbit SSX",
"11":"Bagi, the Monster of Mighty Nature",
"12":"Birth",
"13":"Ai City",
"14":"Roots Search",
"15":"2001 Nights",
"16":"Digital Devil Story: Megami Tensei",
"17":"Akira",
"18":"Appleseed",
"19":"Baoh",
"20":"The Enemy's the Pirates!",
"21":"Gosenzo-sama Banbanzai!",
"22":"Maroko",
"23":"Armored Police Metal Jack",
"24":"Future GPX Cyber Formula",
"25":"Ai no Kusabi",
"26":"8 Man After",
"27":"Big Wars",
"28":"Bio Hunter",
"29":"Apocalypse Zero",
"30":"B't X",
"31":"Birdy the Mighty",
"32":"Agent Aika",
"33":"B't X Neo",
"34":"Battle Athletes",
"35":"Battle Athletes Victory",
"36":"All Purpose Cultural Cat-Girl Nuku Nuku DASH!",
"37":"Cowboy Bebop",
"38":"Yokohama Kaidashi Kikō",
"39":"Amazing Nurse Nanako",
"40":"Infinite Ryvius",
"41":"Seihō Tenshi Angel Links",
"42":"Arc the Lad",
"43":"A.LI.CE",
"44":"Banner of the Stars",
"45":"Alien Nine",
"46":"Angelic Layer",
"47":"Banner of the Stars II",
"48":"6 Angels",
"49":"Astro Boy",
"50":"Avenger",
"51":"Narue no Sekai",
"52":"Azusa, Otetsudai Shimasu!",
"53":"Absolute Boy",
"54":"Aria the Animation",
"55":"Astro Boy: Mighty Atom - Visitor of 100,000 Light Years, IGZA",
"56":"Banner of the Stars III",
"57":"009-1",
"58":"Aria the Natural",
"59":"Aika R-16: Virgin Mission",
"60":"Aria the OVA: Arietta",
"61":"Amuri in Star Ocean",
"62":"Aria the Origination",
"63":"Tetsuwan Birdy: Decode",
"64":"Blassreiter",
"65":"TO",
"66":"Basquash!",
"67":"Tetsuwan Birdy: Decode Season 2",
"68":"Cat Planet Cuties",
"69":"Appleseed XIII",
"70":"Appleseed XIII: Tartaros",
"71":"Appleseed XIII: Ouranos",
"72":"Steins;Gate",
"73":"",
"74":"009 RE:CYBORG",
"75":"AKB0048",
"76":"Ai no Kusabi 2012",
"77":"AKB0048 next stage",
"78":"From the New World",
"79":"Arpeggio of Blue Steel",
"80":"Aruvu Rezuru: Kikaijikake no Yōseitachi",
"81":"Coppelion",
"82":"Double Circle",
"83":"Gatchaman Crowds",
"84":"Valvrave the Liberator",
"85":"Aldnoah.Zero",
"86":"Black Bullet",
"87":"Brynhildr in the Darkness",
"88":"Buddy Complex",
"89":"Captain Earth",
"90":"DRAMAtical Murder",
"91":"Expelled from Paradise",
"92":"Hamatora: The Animation",
"93":"HappinessCharge PreCure!",
"94":"Knights of Sidonia",
"95":"M3 the dark metal",
"96":"Mekakucity Actors",
"97":"Nobunaga the Fool",
"98":"Nobunagun",
"99":"Persona 4: The Golden Animation",
"100":"Selector Infected WIXOSS",
"101":"Space Dandy",
"102":"Sword Art Online II",
"103":"Tokyo ESP",
"104":"Wooser's Hand-to-Mouth Life: Awakening Arc",
"105":"Z/X Ignition",
"106":"Gatchaman Crowds insight",
"107":"Star Twinkle PreCure"
}

romance = {
"1":"1001 Nights",
"2":"5 Centimeters per Second",
"3":"9 Love Stories",
"4":"1st Sorcerous Stabber Orphen",
"5":"A Bridge to the Starry Skies",
"6":"A Dark Rabbit Has Seven Lives",
"7":"A Town Where You Live",
"8":"Adventures of the Little Mermaid",
"9":"Aesthetica of a Rogue Hero",
"10":"Air",
"11":"Aishiteruze Baby",
"12":"Ai Yori Aoshi",
"13":"Ai Yori Aoshi Enishi",
"14":"Akane Maniax",
"15":"Amagami SS",
"16":"Amagami SS+",
"17":"Andersen's Children's Story: The Mermaid Princess",
"18":"Angel Tales",
"19":"Ano Ko ni 1000%",
"20":"Aquarian Age: Sign for Evolution",
"21":"Aquarion Evol",
"22":"Arakawa Under the Bridge",
"23":"Aria the Scarlet Ammo",
"24":"Ashita no Nadja",
"25":"Ask Dr. Rin!",
"26":"Azuki-chan",
"27":"Belladonna of Sadness",
"28":"Beloved Angel Angelique",
"29":"Beyond the Boundary",
"30":"Blue Spring Ride",
"31":"Bobby's In Deep",
"32":"Boys Be",
"33":"Boys Over Flowers",
"34":"Brighter Than the Dawning Blue",
"35":"Brothers Conflict",
"36":"Bronze: Zetsuai Since 1989",
"37":"Candy Candy",
"38":"Cardcaptor Sakura",
"39":"Ceres: Celestial Legend",
"40":"Charlotte (anime)",
"41":"Chibi Vampire",
"42":"Chobits",
"43":"Clannad",
"44":"Da Capo (visual novel)",
"45":"Dance in the Vampire Bund",
"46":"Dance With Devils",
"47":"Darling in the Franxx",
"48":"Date A Live",
"49":"Diabolik Lovers",
"50":"D.N.Angel",
"51":"DNA²",
"52":"Eden of the East",
"53":"Ef - a tale of memories",
"54":"Elfen Lied",
"55":"Engaged to the Unidentified",
"56":"Eureka Seven",
"57":"Fate/stay night",
"58":"Fortune Arterial",
"59":"From Me To You",
"60":"Fruits Basket",
"61":"Full Metal Panic!",
"62":"Full Metal Panic? Fumoffu",
"63":"Full Moon wo Sagashite",
"64":"Fushigi Yugi: The Mysterious Play",
"65":"Future Diary",
"66":"Glasslip",
"67":"Gakuen Alice (Alice Academy or Alice School)",
"68":"Ginban Kaleidoscope",
"69":"Glasslip",
"70":"Golden Time",
"71":"Gosick",
"72":"Guilty Crown",
"73":"He Is My Master",
"74":"Here is Greenwood",
"75":"High School DxD Born",
"76":"His and Her Circumstances",
"77":"Honey and Clover",
"78":"Horizon in the Middle of Nowhere",
"79":"H2O: Footprints in the Sand",
"80":"I My Me! Strawberry Eggs",
"81":"Ichigo 100%",
"82":"If Her Flag Breaks",
"83":"If I See You in My Dreams",
"84":"Inuyasha",
"85":"Inu x Boku SS",
"86":"Is this a zombie?",
"87":"Kamisama Kiss",
"88":"Kanokon: The Girl Who Cried Fox",
"89":"Kanon",
"90":"Kids on the Slope",
"91":"Kimi ni Todoke: From Me to You",
"92":"Kimikiss: Pure Rouge",
"93":"Kirarin Revolution",
"94":"Kodomo no Omocha (Child's Toy),",
"95":"Kokoro Connect",
"96":"Kotoura-san",
"97":"Love, Chunibyo & Other Delusions",
"98":"Lovely Complex",
"99":"Love Hina",
"100":"Magic-Kyun! Renaissance",
"101":"Maiden Spirit Zakuro",
"102":"Maburaho",
"103":"Maison Ikkoku",
"104":"Marmalade Boy",
"105":"Mashiroiro Symphony",
"106":"Mermaid Melody Pichi Pichi Pitch",
"107":"My Guardian Characters",
"108":"My Little Monster",
"109":"My Little Sister Can't Be This Cute!",
"110":"My Love Story!!",
"111":"Myself ; Yourself",
"112":"Mysterious Girlfriend X",
"113":"Nakaimo - My Sister Is Among Them!",
"114":"Nana",
"115":"Neighborhood Story",
"116":"Omamori Himari",
"117":"One Week Friends",
"118":"Ouran High School Host Club",
"119":"Paradise Kiss",
"120":"Peach Girl",
"121":"Place to Place",
"122":"Plastic Memories",
"123":"Playful Kiss",
"124":"Please Teacher",
"125":"Prétear",
"126":"Princess Jellyfish",
"127":"Ranma 1/2",
"128":"Red Data Girl",
"129":"Riddle Story of Devil[1]",
"130":"Rosario + Vampire",
"131":"Samurai Harem: Asu noYoichi",
"132":"Sankarea",
"133":"Say I love you",
"134":"School Days (visual novel)",
"135":"School Rumble",
"136":"Shakugan No Shana",
"137":"Shuffle!",
"138":"Skip Beat!",
"139":"Sugar Sugar Rune",
"140":"Sky With A Rising Half-Moon",
"141":"Snow White with the Red Hair",
"142":"Sola (manga)",
"143":"Song Of The Prince",
"144":"Special A / S · A: Special A",
"145":"Spice and Wolf",
"146":"Suzuka",
"147":"Sword Art Online",
"148":"The Last: Naruto The Movie",
"149":"The Pet Girl of Sakurasou",
"150":"The President is a Maid!",
"151":"The Wallflower",
"152":"The World God Only Knows",
"153":"The World God Only Knows II",
"154":"The World's Greatest First Love",
"155":"To Love-Ru",
"156":"Tokyo Mew Mew",
"157":"Toradora!",
"158":"UFO Baby",
"159":"Ultra Maniac",
"160":"Vampire Knight",
"161":"Waiting in the Summer",
"162":"We were there",
"163":"Witch Craft Works",
"164":"Wolf Girl and Black Prince",
"165":"Yamada-kun and the Seven Witches",
"166":"Yona Of The Dawn"
}

adventure = {
"1":"The Adventures of Hutch the Honeybee",
"2":"The Adventures of Pepero",
"3":"3000 Leagues in Search of Mother",
"4":"The Adventures of the Little Prince",
"5":"3000 Leagues in Search of Mother",
"6":"Acrobunch",
"7":"Adventures of the Little Koala",
"8":"The Adventures of Scamper the Penguin",
"9":"The Adventures of Peter Pan",
"10":"801 T.T.S. Airbats",
"11":"Agent Aika",
"12":"Sorcerous Stabber Orphen: Beginning",
"13":"Sorcerous Stabber Orphen: Revenge",
"14":"Marco: 3000 Leagues in Search of Mother",
"15":"Inuyasha",
"16":"10 Tokyo Warriors",
"17":"Tweeny Witches",
"18":"Aika R-16: Virgin Mission",
"19":"Gurren Lagann",
"20":"Tweeny Witches: The Adventure",
"21":"009 RE:CYBORG",
"22":"The Seven Deadly Sins",
"23":"Sorcerous Stabber Orphen: Wayward Journey"
}

psychological = {
"1":"As the Gods Will",
"2":"B The Beginning",
"3":"Boogiepop Phantom",
"4":"Death Note",
"5":"Doreiku",
"6":"Freesia (manga)",
"7":"Future Diary",
"8":"Gantz",
"9":"Happy Sugar Life",
"10":"Hell's Paradise: Jigokuraku",
"11":"I Am a Hero",
"12":"Ikigami: The Ultimate Limit",
"13":"The Laughing Salesman",
"14":"Liar Game",
"15":"Lupin the Third: The Woman Called Fujiko Mine",
"16":"Magia Record",
"17":"Monster (manga)",
"18":"Old Boy (manga)",
"19":"Paprika (2006 film)",
"20":"Paranoia Agent",
"21":"Perfect Blue",
"22":"Pet (manga)",
"23":"Psycho-Pass",
"24":"Puella Magi Madoka Magica",
"25":"School-Live!",
"26":"Shiki (novel)",
"27":"Steins;Gate (TV series)",
"28":"Talentless Nana",
"29":"Telepathic Wanderers"
}

comedy = {
"1":"Urusei Yatsura",
"2":"Ranma 1/2",
"3":"Ranma 1/2 Nettōhen",
"4":"Gosenzo-sama Banbanzai!",
"5":"Maroko",
"6":"Kyō Kara Ore Wa!!",
"7":"Sorcerous Stabber Orphen: Beginning",
"8":"Sorcerous Stabber Orphen: Revenge",
"9":"Ghost Stories",
"10":"Azumanga Daioh: The Animation",
"11":"Bobobo-bo Bo-bobo",
"12":"Cromartie High School",
"13":"Bludgeoning Angel Dokuro-Chan",
"14":"Minami-ke",
"15":"Sketchbook ~full color's~",
"16":"Minami-ke: Okawari",
"17":"Gintama",
"18":"Hetalia: Axis Powers",
"19":"Minami-ke: Betsubara",
"20":"Minami-ke: Okaeri",
"21":"Baka and Test",
"22":"Mitsudomoe",
"23":"Sket Dance",
"24":"Minami-ke: Omatase",
"25":"Acchi Kocchi",
"26":"Kotoura-san",
"27":"Minami-ke: Tadaima",
"28":"Minami-ke: Natsuyasumi",
"29":"D-Frag!",
"30":"Engaged to the Unidentified",
"31":"Hōzuki no Reitetsu",
"32":"Inari, Konkon, Koi Iroha",
"33":"Love, Chunibyo and Other Delusions! -Heart Throb-",
"34":"Minna Atsumare! Falcom beep Gakuen",
"35":"Tonari no Seki-kun: The Master of Killing Time",
"36":"Nisekoi",
"37":"No-Rin",
"38":"Oneechan ga Kita",
"39":"Go! Go! 575",
"40":"Pupipō!",
"41":"Recently, My Sister Is Unusual",
"42":"Robot Girls Z",
"43":"Seitokai Yakuindomo*",
"44":"Silver Spoon Season 2",
"45":"Space Dandy"
}

drama = {
"1":"3000 Leagues in Search of Mother",
"2":"3000 Leagues in Search of Mother",
"3":"Ai no Gakko Cuore Monogatari",
"4":"Gosenzo-sama Banbanzai!",
"5":"Maroko",
"6":"Sorcerous Stabber Orphen: Beginning",
"7":"Sorcerous Stabber Orphen: Revenge",
"8":"Ah! My Goddess: The Movie",
"9":"Air",
"10":"Aria The Animation",
"11":"Aria The Natural",
"12":"Clannad",
"13":"5 Centimeters Per Second",
"14":"Aria the OVA: Arietta",
"15":"Clannad",
"16":"Clannad Another World: Tomoyo Chapter",
"17":"Aria The Origination",
"18":"Akaneiro ni Somaru Saka",
"19":"Clannad After Story",
"20":"Clannad Another World: Kyou Chapter",
"21":"A Letter to Momo",
"22":"009 Re:Cyborg",
"23":"The Pilot's Love Song",
"24":"Sorcerous Stabber Orphen: Wayward Journey"
}

fantasy = {
"1":"Sailor Moon",
"2":"Sailor Moon Crystal",
"3":"Saint October",
"4":"Saint Tail (Kaitou Saint Tail)",
"5":"Sakura Wars",
"6":"Samurai Champloo",
"7":"Samurai Girl: Real Bout High School",
"8":"Sanzoku no Musume Rōnya",
"9":"Scrapped Princess",
"10":"Seisen Cerberus",
"11":"Seraph of the End",
"12":"Shakugan no Shana",
"13":"Shamanic Princess",
"14":"Shattered Angels (Kyōshirō to Towa no Sora)",
"15":"Shigofumi: Letters from the Departed",
"16":"Shin Angyo Onshi",
"17":"Shining Tears X Wind",
"18":"Shinkyoku Sōkai Polyphonica",
"19":"Shugo Chara!",
"20":"Shuffle!",
"21":"Sisters of Wellber",
"22":"Slayers",
"23":"Smile PreCure! (Smile Pretty Cure!)",
"24":"Sola",
"25":"Someday's Dreamers",
"26":"Sorcerer Hunters",
"27":"Sorcerous Stabber Orphen: Beginning",
"28":"Sorcerous Stabber Orphen: Revenge[48]",
"29":"Sorcerous Stabber Orphen: Wayward Journey (2020)",
"30":"Soul Eater",
"31":"Spice and Wolf",
"32":"Spirited Away (Sen to Chihiro no Kamikakushi)",
"33":"Strange Dawn",
"34":"Strike the Blood",
"35":"Sugar Sugar Rune",
"36":"Suite PreCure",
"37":"Sword Art Online",
"38":"Rage of Bahamut: Genesis (Shingeki no Bahamut Genesis)",
"39":"Ragnarok the Animation",
"40":"Rakudai Kishi no Cavalry",
"41":"Rakugo Tennyo Oyui",
"42":"Ranma ½",
"43":"Rave Master",
"44":"Record of Lodoss War",
"45":"Renkin 3-kyū Magical? Pokān",
"46":"Rental Magica",
"47":"Revolutionary Girl Utena (Shoujo Kakumei Utena)",
"48":"Re:Zero kara Hajimeru Isekai Seikatsu",
"49":"RG Veda",
"50":"Romeo × Juliet",
"51":"Ronin Warriors (Yoroiden Samurai Troopers)",
"52":"Rozen Maiden",
"53":"Ruin Explorers (Hikyou Tanken ...)",
"54":"Rune Soldier (Magical Soldier Louie)",
"55":"Rosario + Vampire",
"56":"Tai-Madō Gakuen 35 Shiken Shōtai",
"57":"Tales from Earthsea",
"58":"Tales of the Abyss",
"59":"Tales of Phantasia: The Animation",
"60":"Tales of Symphonia",
"61":"Tales of Zestiria the X",
"62":"Tatsu no ko Taro (Taro the Dragon Boy)",
"63":"Tayutama: Kiss on my Deity",
"64":"Tears to Tiara",
"65":"Tenbatsu! Angel Rabbie (Heaven's Judgement! XX Angel Rabbie)",
"66":"Tenkai Knights",
"67":"The Betrayal Knows My Name (Uragiri wa Boku no Namae o Shitteiru)",
"68":"The Cat Returns",
"69":"The Cosmopolitan Prayers",
"70":"The Devil Is a Part-Timer",
"71":"The Familiar of Zero (Zero no Tsukaima)",
"72":"The Great Adventure of Horus, Prince of the Sun",
"73":"The Good Witch of the West",
"74":"The Heroic Legend of Arslan",
"75":"The Irregular at Magic High School",
"76":"The Law of Ueki",
"77":"The Legend of the Legendary Heroes",
"78":"The Mythical Detective Loki Ragnarok",
"79":"The Pilot's Love Song",
"80":"The Rising of the Shield Hero",
"81":"The Sea Prince and the Fire Child",
"82":"The Seven Deadly Sins",
"83":"The Severing Crime Edge",
"84":"The Snow Queen",
"85":"The Story of Saiunkoku (Saiunkoku Monogatari)",
"86":"The Testament of Sister New Devil",
"87":"The Tower of Druaga",
"88":"The Twelve Kingdoms (Jūni Kokuki)",
"89":"The Vision of Escaflowne",
"90":"The World God Only Knows",
"91":"The World Is Still Beautiful (Soredemo Sekai wa Utsukushii)",
"92":"Those Who Hunt Elves",
"93":"Tōka Gettan",
"94":"Tokyo Mew Mew",
"95":"Tokyo Babylon",
"96":"Tokyo Ghoul",
"97":"Tokyo Ravens",
"98":"Trigun",
"99":"Trinity Seven",
"100":"Tsubasa: Reservoir Chronicle",
"101":"Tweeny Witches (Mahou Shoujo Tai Arusu)",
"102":"Fairy Tail",
"103":"Fancy Lala (Mahō no Stage Fancy Lala)",
"104":"Fate/kaleid liner Prisma Illya",
"105":"Fate/stay night",
"106":"Fate/Zero",
"107":"Fighting Foodons",
"108":"Final Fantasy: Legend of the Crystals",
"109":"Final Fantasy: Unlimited",
"110":"Final Fantasy VII: Last Order",
"111":"Fire Emblem",
"112":"Flame of Recca (Rekka no Honō)",
"113":"Fruits Basket",
"114":"Full Moon o Sagashite (In Search of the Full Moon)",
"115":"Fullmetal Alchemist (Hagane no Renkinjutsushi)",
"116":"Fullmetal Alchemist: Brotherhood",
"117":"Fushigi Yûgi (Fushigi Yûgi: The Mysterious Play)",
"118":"Fushigiboshi no Futagohime (Twin Princesses of the Wonder Planet)",
"119":"Futari wa Pretty Cure",
"120":"D.Gray-man",
"121":"D.N.Angel",
"122":"Da Capo",
"123":"Da Capo II",
"124":"Da Capo III",
"125":"Damekko Dōbutsu",
"126":"Date A Live",
"127":"Death Note",
"128":"Deltora Quest",
"129":"Demon Slayer",
"130":"Descendants of Darkness (Yami no Matsuei)",
"131":"Detatoko Princess",
"132":"Di Gi Charat",
"133":"Dinosaur King",
"134":"Dog Days",
"135":"Dragon Ball",
"136":"Dragon Ball Z",
"137":"Dragon Ball Super",
"138":"Dragon Crisis!",
"139":"Dragon Drive",
"140":"Dragon Half",
"141":"Dragon Quest",
"142":"Dragon Quest: Dai no Daibōken",
"143":"Dragon Quest: Emblem of Roto",
"144":"Dragonaut: The Resonance",
"145":"Dream Eater Merry (Yumekui Merī)",
"146":"Yami to Bōshi to Hon no Tabibito (Darkness, the Hat, and the Travelers of the Books, Yamibō)",
"147":"Yo-Kai Watch",
"148":"Yoshinaga-san Chi no Gargoyle",
"149":"Yōtōden",
"150":"Yumeria",
"151":"Ys",
"152":"Yu-Gi-Oh!",
"153":"Yu-Gi-Oh! GX",
"154":"Yu-Gi-Oh! 5D's",
"155":"Yu-Gi-Oh! Zexal",
"156":"Yu-Gi-Oh! Arc-V",
"157":"Yu-Gi-Oh! VRAINS",
"158":"Yu-Gi-Oh! Sevens",
"159":"Yurikuma Arashi",
"160":"Yu Yu Hakusho"
}


